export const options = [
  { value: "Choose a model", label: "Виберіть модель" },
  { value: "overall", label: "комбінезон" },
  { value: "vest", label: "Жилет" },
  { value: "blanket", label: "Попон" },
  { value: "jacket", label: "Куртк" },
  { value: "suit", label: "Костюм" },
  { value: "skinny", label: "Худі" },
  { value: "bomber", label: "Бомбер" },
  { value: "sweatshirt", label: "Світшот" },
  { value: "trousers", label: "штанці" },
  { value: "hats", label: "Шапка" },
  { value: "scarves", label: "Шарф" },
  { value: "tShirt", label: "Футболка" },
  { value: "singlet", label: "Майка" },
  { value: "shirt", label: "Сорочка" },
  { value: "embroidery", label: "Вишиванка" },
  { value: "dress", label: "Сукня" },
  { value: "skirt", label: "Спідниця" },
  { value: "briefs", label: "Гігієнічні труси" },
];
