const clothesMenu = [
  { id: 1, title: "Overalls", page: "1", type: "overall", parent: "1" },
  {
    id: 2,
    title: "Vest",
    page: "1",
    type: "vest",
    parent: "2",
  },
  {
    id: 3,
    title: "Blanket",
    page: "1",
    type: "blanket",
    parent: "2",
  },
  {
    id: 4,
    title: "Jacket",
    page: "1",
    type: "jacket",
    parent: "3",
  },
  { id: 5, title: "Suits", page: "1", type: "suits", parent: "4" },

  // {
  //   id: 6,
  //   title: "Skinny",
  //   page: "1",
  //   type: "skinny",
  // },
  {
    id: 7,
    title: "Bomber",
    page: "1",
    type: "bomber",
    parent: "5",
  },
  {
    id: 19,
    title: "Hoodies",
    page: "1",
    type: "hoodies",
    parent: "5",
  },
  {
    id: 8,
    title: "Sweatshirt",
    page: "1",
    type: "sweatshirt",
    parent: "5",
  },
  {
    id: 9,
    title: "Trousers",
    page: "1",
    type: "trousers",
    parent: "6",
  },
  { id: 10, title: "Hats", page: "1", type: "hats", parent: "7" },
  {
    id: 11,
    title: "Scarves",
    page: "1",
    type: "scarves",
    parent: "7",
  },
  {
    id: 12,
    title: "T-shirts",
    page: "1",
    type: "tShirt",
    parent: "8",
  },
  {
    id: 13,
    title: "Singlet",
    page: "1",
    type: "singlet",
    parent: "8",
  },
  { id: 14, title: "Shirt", page: "1", type: "shirt", parent: "9" },
  {
    id: 15,
    title: "Embroidery",
    page: "1",
    type: "embroidery",
    parent: "9",
  },
  { id: 16, title: "Dress", page: "1", type: "dress", parent: "10" },
  { id: 17, title: "Skirt", page: "1", type: "skirt", parent: "10" },
  {
    id: 18,
    title: "Briefs",
    page: "1",
    type: "briefs",
    parent: "11",
  },

  {
    id: 20,
    title: "Footwear",
    page: "1",
    type: "footwear",
    parent: "12",
  },
  { id: 21, title: "Couch", page: "1", type: "couch", parent: "13" },
];

export default clothesMenu;
