// const clothesMenu = [
//   { id: 1, title: "Overalls", path: "/clothes/overalls" },
//   { id: 2, title: "Vest", path: "/clothes/vest" },
//   { id: 3, title: "Blanket", path: "/clothes/blanket" },
//   { id: 4, title: "Jacket", path: "/clothes/jacket" },
//   { id: 5, title: "Suits", path: "/clothes/suits" },
//   { id: 6, title: "Skinny", path: "/clothes/skinny" },
//   { id: 7, title: "Bomber", path: "/clothes/bomber" },
//   { id: 8, title: "Sweatshirt", path: "/clothes/sweatshirt" },
//   { id: 9, title: "Trousers", path: "/clothes/trousers" },
//   { id: 10, title: "Hats", path: "/clothes/hats" },
//   { id: 11, title: "Scarves", path: "/clothes/scarves" },
//   { id: 12, title: "T-shirts", path: "/clothes/tShirt" },
//   { id: 13, title: "Singlet", path: "/clothes/singlet" },
//   { id: 14, title: "Shirt", path: "/clothes/shirt" },
//   { id: 15, title: "Embroidery", path: "/clothes/embroidery" },
//   { id: 16, title: "Dress", path: "/clothes/dress" },
//   { id: 17, title: "Skirt", path: "/clothes/skirt" },
//   { id: 18, title: "Briefs", path: "/clothes/briefs" },
//   { id: 19, title: "Hoodies", path: "/clothes/hoodies" },
//   { id: 20, title: "Footwear", path: "/clothes/footwear" },
//   { id: 21, title: "Couch", path: "/clothes/couch" },
// ];
const clothesMenu = [
  { id: 1, title: "Overalls", page: "1", type: "overalls" },
  {
    id: 2,
    title: "Vest",
    page: "1",
    type: "vest",
  },
  {
    id: 3,
    title: "Blanket",
    page: "1",
    type: "blanket",
  },
  {
    id: 4,
    title: "Jacket",
    page: "1",
    type: "jacket",
  },
  { id: 5, title: "Suits", page: "1", type: "suits" },
  {
    id: 6,
    title: "Skinny",
    page: "1",
    type: "skinny",
  },
  {
    id: 7,
    title: "Bomber",
    page: "1",
    type: "bomber",
  },
  {
    id: 8,
    title: "Sweatshirt",
    page: "1",
    type: "sweatshirt",
  },
  {
    id: 9,
    title: "Trousers",
    page: "1",
    type: "trousers",
  },
  { id: 10, title: "Hats", page: "1", type: "hats" },
  {
    id: 11,
    title: "Scarves",
    page: "1",
    type: "scarves",
  },
  {
    id: 12,
    title: "T-shirts",
    page: "1",
    type: "tShirt",
  },
  {
    id: 13,
    title: "Singlet",
    page: "1",
    type: "singlet",
  },
  { id: 14, title: "Shirt", page: "1", type: "shirt" },
  {
    id: 15,
    title: "Embroidery",
    page: "1",
    type: "embroidery",
  },
  { id: 16, title: "Dress", page: "1", type: "dress" },
  { id: 17, title: "Skirt", page: "1", type: "skirt" },
  {
    id: 18,
    title: "Briefs",
    page: "1",
    type: "briefs",
  },
  {
    id: 19,
    title: "Hoodies",
    page: "1",
    type: "hoodies",
  },
  {
    id: 20,
    title: "Footwear",
    page: "1",
    type: "footwear",
  },
  { id: 21, title: "Couch", page: "1", type: "couch" },
];

export default clothesMenu;
